spring:
  application:
    name: inventory-service
  config:
    import: "configserver:"
  cloud:
    config:
      uri: http://config.platform:9000

server:
  port: 8001
  servlet:
    session:
      persistent: false